usuario_add:
  path:     /add/
  defaults: { _controller: AdminBundle:User:usuarioAdd }

usuario_delete:
  path:     /delete/{id}/
  defaults: { _controller: AdminBundle:User:usuarioDelete }

usuario_edit:
  path:     /edit/{id}/
  defaults: { _controller: AdminBundle:User:usuarioEdit }

usuario_show:
  path:     /show/
  defaults: { _controller: AdminBundle:User:usuarioShow }