login:
    path: /
    defaults: { _controller: AdminBundle:User:login }

_login:
    path: /login/
    defaults: { _controller: AdminBundle:User:login }

login_check:
    path: /login_check/

logout:
    path: /logout/

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin