# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AdminBundle\Entity\User:
            algorithm: sha512
            iterations: 5
            encode_as_base64: true

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            entity:
                class: AdminBundle:User
                property: name

    firewalls:
        main:
            anonymous: ~
            pattern: ^/
            provider: user_db
            form_login:
                check_path: login_check
                login_path: login
                use_referer: true
            logout:
                path: /logout/
                target: /login/}

    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/*, roles: [ROLE_ADMIN] }
